-- =====================================================================
-- MIGRATION: Drops and recreates everything cleanly
-- WARNING: This will delete all existing data in agents and verification_logs
-- =====================================================================

-- Step 1: Drop dependent objects first (views depend on tables)
DROP VIEW IF EXISTS agent_stats CASCADE;

-- Step 2: Drop tables (CASCADE will drop any dependent objects)
DROP TABLE IF EXISTS webhook_endpoints CASCADE;
DROP TABLE IF EXISTS verification_logs CASCADE;
DROP TABLE IF EXISTS agents CASCADE;

-- Step 3: Create agents table
CREATE TABLE agents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id VARCHAR(50) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  owner_email VARCHAR(255) NOT NULL,
  api_key_hash VARCHAR(64) NOT NULL,
  refresh_token_hash TEXT,
  refresh_token_expires_at TIMESTAMP WITH TIME ZONE,
  permissions TEXT[] DEFAULT '{"read"}',
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended', 'revoked')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  last_verified_at TIMESTAMP WITH TIME ZONE,
  metadata JSONB DEFAULT '{}'
);

-- Step 4: Create verification_logs table
CREATE TABLE verification_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id VARCHAR(50) NOT NULL,
  success BOOLEAN NOT NULL,
  reason VARCHAR(50),
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ip_address VARCHAR(45)
);

-- Webhook endpoints for event notifications
CREATE TABLE IF NOT EXISTS webhook_endpoints (
  id SERIAL PRIMARY KEY,
  agent_id VARCHAR(50) REFERENCES agents(agent_id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  events TEXT[] NOT NULL,
  secret VARCHAR(64) NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add tier column to agents (if upgrading existing database)
ALTER TABLE agents ADD COLUMN IF NOT EXISTS tier VARCHAR(20) DEFAULT 'free' CHECK (tier IN ('free', 'pro', 'enterprise'));

-- Step 5: Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_agents_agent_id ON agents(agent_id);
CREATE INDEX IF NOT EXISTS idx_agents_owner_email ON agents(owner_email);
CREATE INDEX IF NOT EXISTS idx_agents_status ON agents(status);
CREATE INDEX IF NOT EXISTS idx_agents_refresh_token_hash ON agents(refresh_token_hash);
CREATE INDEX IF NOT EXISTS idx_verification_logs_agent_id ON verification_logs(agent_id);
CREATE INDEX IF NOT EXISTS idx_verification_logs_timestamp ON verification_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_webhook_endpoints_agent_id ON webhook_endpoints(agent_id);
CREATE INDEX IF NOT EXISTS idx_verification_logs_ip_address ON verification_logs(ip_address);

-- Step 6: Create the view
CREATE VIEW agent_stats AS
SELECT
  a.agent_id,
  a.name,
  a.status,
  a.created_at,
  COUNT(v.id) as total_verifications,
  COUNT(CASE WHEN v.success = true THEN 1 END) as successful_verifications,
  MAX(v.timestamp) as last_verification_attempt
FROM agents a
LEFT JOIN verification_logs v ON a.agent_id = v.agent_id
GROUP BY a.agent_id, a.name, a.status, a.created_at;

-- =====================================================================
-- VERIFICATION QUERIES (run these after the migration)
-- =====================================================================

-- Verify tables exist with correct columns:
SELECT table_name, column_name, data_type
FROM information_schema.columns
WHERE table_name IN ('agents','verification_logs')
ORDER BY table_name, ordinal_position;

-- Verify the view definition:
SELECT definition FROM pg_views WHERE viewname = 'agent_stats' AND schemaname = 'public';

-- Test the view (should return empty result set):
SELECT * FROM agent_stats LIMIT 5;
