-- AgentAuths Database Schema
-- Fixed version with correct column names matching the application code

-- Agents table
CREATE TABLE IF NOT EXISTS agents (
  id SERIAL PRIMARY KEY,
  agent_id VARCHAR(50) UNIQUE NOT NULL,  -- Changed from 'agentauth' to match code
  name VARCHAR(255) NOT NULL,
  description TEXT,
  owner_email VARCHAR(255) NOT NULL,
  api_key_hash VARCHAR(64) NOT NULL,
  refresh_token_hash TEXT,
  refresh_token_expires_at TIMESTAMP WITH TIME ZONE,
  permissions TEXT[] DEFAULT ARRAY['read'],
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended', 'revoked')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  last_verified_at TIMESTAMP WITH TIME ZONE,
  metadata JSONB DEFAULT '{}',
  tier VARCHAR(20) DEFAULT 'free' CHECK (tier IN ('free', 'pro', 'enterprise'))
);

-- Verification logs (for analytics & security)
CREATE TABLE IF NOT EXISTS verification_logs (
  id SERIAL PRIMARY KEY,
  agent_id VARCHAR(50) NOT NULL,  -- Changed from 'agentauth' to match code
  success BOOLEAN NOT NULL,
  reason VARCHAR(50),
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ip_address VARCHAR(45)
);

-- Webhook endpoints for event notifications
CREATE TABLE IF NOT EXISTS webhook_endpoints (
  id SERIAL PRIMARY KEY,
  agent_id VARCHAR(50) REFERENCES agents(agent_id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  events TEXT[] NOT NULL,  -- ['agent.registered', 'agent.verified', 'agent.revoked']
  secret VARCHAR(64) NOT NULL,  -- For HMAC signature
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_agents_agent_id ON agents(agent_id);  -- Updated index name
CREATE INDEX IF NOT EXISTS idx_agents_owner_email ON agents(owner_email);
CREATE INDEX IF NOT EXISTS idx_agents_status ON agents(status);
CREATE INDEX IF NOT EXISTS idx_agents_refresh_token_hash ON agents(refresh_token_hash);
CREATE INDEX IF NOT EXISTS idx_verification_logs_agent_id ON verification_logs(agent_id);  -- Updated index name
CREATE INDEX IF NOT EXISTS idx_verification_logs_timestamp ON verification_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_webhook_endpoints_agent_id ON webhook_endpoints(agent_id);

-- Row Level Security (RLS)
-- Note: Since we're using the service role key (anon key) from the server,
-- these policies allow full access. RLS adds defense-in-depth in case credentials leak.
ALTER TABLE agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE verification_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Allow service role full access to agents
CREATE POLICY "Service role has full access to agents" ON agents
  FOR ALL
  TO anon
  USING (true)
  WITH CHECK (true);

-- Policy: Allow service role full access to verification_logs
CREATE POLICY "Service role has full access to verification_logs" ON verification_logs
  FOR ALL
  TO anon
  USING (true)
  WITH CHECK (true);

ALTER TABLE webhook_endpoints ENABLE ROW LEVEL SECURITY;

-- Policy: Allow service role full access to webhook_endpoints
CREATE POLICY "Service role has full access to webhook_endpoints" ON webhook_endpoints
  FOR ALL
  TO anon
  USING (true)
  WITH CHECK (true);

-- Example: View for agent stats (useful later for dashboard)
CREATE OR REPLACE VIEW agent_stats AS
SELECT
  a.agent_id,  -- Changed from 'agentauth'
  a.name,
  a.status,
  a.created_at,
  COUNT(v.id) as total_verifications,
  COUNT(CASE WHEN v.success = true THEN 1 END) as successful_verifications,
  MAX(v.timestamp) as last_verification_attempt
FROM agents a
LEFT JOIN verification_logs v ON a.agent_id = v.agent_id  -- Updated join condition
GROUP BY a.agent_id, a.name, a.status, a.created_at;  -- Updated group by

-- =============================================================================
-- Soul Layer tables (v0.7.0)
-- See migrations/002_soul_layer.sql for the full migration script.
-- =============================================================================

-- Drift health pings — self-reported behavioral metrics per reporting period
CREATE TABLE IF NOT EXISTS drift_health_pings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id VARCHAR(50) NOT NULL REFERENCES agents(agent_id) ON DELETE CASCADE,
  metrics JSONB,
  request_count INTEGER,
  period_start TIMESTAMPTZ,
  period_end TIMESTAMPTZ,
  drift_score NUMERIC(5,4) CHECK (drift_score BETWEEN 0 AND 1),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Drift configs — one config per agent for drift detection thresholds
CREATE TABLE IF NOT EXISTS drift_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id VARCHAR(50) NOT NULL UNIQUE REFERENCES agents(agent_id) ON DELETE CASCADE,
  drift_threshold NUMERIC(5,4) DEFAULT 0.30 CHECK (drift_threshold BETWEEN 0 AND 1),
  warning_threshold NUMERIC(5,4) DEFAULT 0.24 CHECK (warning_threshold BETWEEN 0 AND 1),
  auto_revoke BOOLEAN DEFAULT true,
  metric_weights JSONB,
  baseline_metrics JSONB,
  spike_sensitivity NUMERIC(3,1) DEFAULT 2.0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT warning_below_drift CHECK (warning_threshold < drift_threshold)
);

-- ZKP commitments — anonymous verification commitment store
CREATE TABLE IF NOT EXISTS zkp_commitments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  commitment VARCHAR(256) UNIQUE NOT NULL,
  permissions TEXT[],
  tier VARCHAR(20),
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Persona history — immutable audit trail of persona changes
CREATE TABLE IF NOT EXISTS persona_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id VARCHAR(50) NOT NULL REFERENCES agents(agent_id) ON DELETE CASCADE,
  persona JSONB,
  persona_hash VARCHAR(64),
  persona_version VARCHAR(10),
  changed_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for Soul Layer tables
CREATE INDEX IF NOT EXISTS idx_drift_health_pings_agent_id ON drift_health_pings(agent_id);
CREATE INDEX IF NOT EXISTS idx_drift_health_pings_period_start ON drift_health_pings(period_start);
CREATE INDEX IF NOT EXISTS idx_drift_health_pings_agent_id_created_at ON drift_health_pings(agent_id, created_at);
CREATE INDEX IF NOT EXISTS idx_drift_configs_agent_id ON drift_configs(agent_id);
CREATE INDEX IF NOT EXISTS idx_zkp_commitments_commitment ON zkp_commitments(commitment);
CREATE INDEX IF NOT EXISTS idx_zkp_commitments_expires_at ON zkp_commitments(expires_at);
CREATE INDEX IF NOT EXISTS idx_agents_persona_hash ON agents(persona_hash);
CREATE INDEX IF NOT EXISTS idx_persona_history_agent_id_changed_at ON persona_history(agent_id, changed_at);

-- RLS for Soul Layer tables
ALTER TABLE drift_health_pings ENABLE ROW LEVEL SECURITY;
ALTER TABLE drift_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE zkp_commitments ENABLE ROW LEVEL SECURITY;
ALTER TABLE persona_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role has full access to drift_health_pings" ON drift_health_pings
  FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE POLICY "Service role has full access to drift_configs" ON drift_configs
  FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE POLICY "Service role has full access to zkp_commitments" ON zkp_commitments
  FOR ALL TO anon USING (true) WITH CHECK (true);

CREATE POLICY "Service role has full access to persona_history" ON persona_history
  FOR ALL TO anon USING (true) WITH CHECK (true);

-- Active commitments view
CREATE OR REPLACE VIEW active_commitments AS
SELECT *
FROM zkp_commitments
WHERE status = 'active'
  AND (expires_at IS NULL OR expires_at > NOW());

-- Drift summary view (feeds dashboard overview)
CREATE OR REPLACE VIEW drift_summary AS
SELECT
  a.agent_id,
  a.name,
  a.status,
  dc.drift_threshold,
  dc.warning_threshold,
  (
    SELECT drift_score
    FROM drift_health_pings
    WHERE agent_id = a.agent_id
    ORDER BY created_at DESC
    LIMIT 1
  ) AS latest_drift_score,
  (
    SELECT AVG(drift_score)
    FROM drift_health_pings
    WHERE agent_id = a.agent_id
  ) AS avg_drift_score,
  (
    SELECT COUNT(*)
    FROM drift_health_pings
    WHERE agent_id = a.agent_id
  ) AS total_pings
FROM agents a
LEFT JOIN drift_configs dc ON a.agent_id = dc.agent_id;
