-- =============================================================================
-- Migration 002: Soul Layer (AgentAuth v0.7.0)
-- Adds: Persona System, ZKP Anonymous Verification, Anti-Drift Vault
-- All statements use IF NOT EXISTS / OR REPLACE for idempotent reruns.
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. New columns on agents table
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE agents ADD COLUMN IF NOT EXISTS persona JSONB;
ALTER TABLE agents ADD COLUMN IF NOT EXISTS persona_hash VARCHAR(64);
ALTER TABLE agents ADD COLUMN IF NOT EXISTS persona_version VARCHAR(10);
ALTER TABLE agents ADD COLUMN IF NOT EXISTS zkp_commitment VARCHAR(128);
ALTER TABLE agents ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Auto-update trigger function
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE 'plpgsql';

-- Agents trigger (only fires on actual changes)
DROP TRIGGER IF EXISTS update_agents_updated_at ON agents;
CREATE TRIGGER update_agents_updated_at
  BEFORE UPDATE ON agents
  FOR EACH ROW
  WHEN (OLD.* IS DISTINCT FROM NEW.*)
  EXECUTE FUNCTION update_updated_at_column();

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. New table: drift_health_pings
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS drift_health_pings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id VARCHAR(50) NOT NULL REFERENCES agents(agent_id) ON DELETE CASCADE,
  metrics JSONB,
  request_count INTEGER,
  period_start TIMESTAMPTZ,
  period_end TIMESTAMPTZ,
  drift_score NUMERIC(5,4) CHECK (drift_score BETWEEN 0 AND 1),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. New table: drift_configs
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS drift_configs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id VARCHAR(50) NOT NULL UNIQUE REFERENCES agents(agent_id) ON DELETE CASCADE,
  drift_threshold NUMERIC(5,4) DEFAULT 0.30 CHECK (drift_threshold BETWEEN 0 AND 1),
  warning_threshold NUMERIC(5,4) DEFAULT 0.24 CHECK (warning_threshold BETWEEN 0 AND 1),
  auto_revoke BOOLEAN DEFAULT true,
  metric_weights JSONB,
  baseline_metrics JSONB,
  spike_sensitivity NUMERIC(3,1) DEFAULT 2.0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT warning_below_drift CHECK (warning_threshold < drift_threshold)
);

-- Drift configs trigger (reuses the same function)
DROP TRIGGER IF EXISTS update_drift_configs_updated_at ON drift_configs;
CREATE TRIGGER update_drift_configs_updated_at
  BEFORE UPDATE ON drift_configs
  FOR EACH ROW
  WHEN (OLD.* IS DISTINCT FROM NEW.*)
  EXECUTE FUNCTION update_updated_at_column();

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. New table: zkp_commitments
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS zkp_commitments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  commitment VARCHAR(256) UNIQUE NOT NULL,
  permissions TEXT[],
  tier VARCHAR(20),
  status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. New table: persona_history
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS persona_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id VARCHAR(50) NOT NULL REFERENCES agents(agent_id) ON DELETE CASCADE,
  persona JSONB,
  persona_hash VARCHAR(64),
  persona_version VARCHAR(10),
  changed_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 7. Constraints
-- ─────────────────────────────────────────────────────────────────────────────

-- Unique persona hash per agent (prevent hash collisions per agent)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'uq_agents_agent_id_persona_hash'
  ) THEN
    ALTER TABLE agents ADD CONSTRAINT uq_agents_agent_id_persona_hash
      UNIQUE (agent_id, persona_hash);
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 8. Indexes
-- ─────────────────────────────────────────────────────────────────────────────

-- drift_health_pings indexes
CREATE INDEX IF NOT EXISTS idx_drift_health_pings_agent_id
  ON drift_health_pings(agent_id);
CREATE INDEX IF NOT EXISTS idx_drift_health_pings_period_start
  ON drift_health_pings(period_start);
CREATE INDEX IF NOT EXISTS idx_drift_health_pings_agent_id_created_at
  ON drift_health_pings(agent_id, created_at);

-- drift_configs indexes
CREATE INDEX IF NOT EXISTS idx_drift_configs_agent_id
  ON drift_configs(agent_id);

-- zkp_commitments indexes
CREATE INDEX IF NOT EXISTS idx_zkp_commitments_commitment
  ON zkp_commitments(commitment);
CREATE INDEX IF NOT EXISTS idx_zkp_commitments_expires_at
  ON zkp_commitments(expires_at);

-- agents indexes (new columns)
CREATE INDEX IF NOT EXISTS idx_agents_persona_hash
  ON agents(persona_hash);

-- persona_history indexes
CREATE INDEX IF NOT EXISTS idx_persona_history_agent_id_changed_at
  ON persona_history(agent_id, changed_at);

-- ─────────────────────────────────────────────────────────────────────────────
-- 9. Views
-- ─────────────────────────────────────────────────────────────────────────────

-- Active commitments (filter out expired and revoked)
CREATE OR REPLACE VIEW active_commitments AS
SELECT *
FROM zkp_commitments
WHERE status = 'active'
  AND (expires_at IS NULL OR expires_at > NOW());

-- Drift summary per agent (feeds dashboard overview)
CREATE OR REPLACE VIEW drift_summary AS
SELECT
  a.agent_id,
  a.name,
  a.status,
  dc.drift_threshold,
  dc.warning_threshold,
  (
    SELECT drift_score
    FROM drift_health_pings
    WHERE agent_id = a.agent_id
    ORDER BY created_at DESC
    LIMIT 1
  ) AS latest_drift_score,
  (
    SELECT AVG(drift_score)
    FROM drift_health_pings
    WHERE agent_id = a.agent_id
  ) AS avg_drift_score,
  (
    SELECT COUNT(*)
    FROM drift_health_pings
    WHERE agent_id = a.agent_id
  ) AS total_pings
FROM agents a
LEFT JOIN drift_configs dc ON a.agent_id = dc.agent_id;

-- ─────────────────────────────────────────────────────────────────────────────
-- 10. Backfill existing agents
-- ─────────────────────────────────────────────────────────────────────────────

-- Set new columns to NULL for existing agents that don't have them
UPDATE agents
SET persona = NULL,
    persona_hash = NULL,
    persona_version = NULL,
    zkp_commitment = NULL
WHERE persona IS NULL;

-- Default drift configs for all agents (idempotent via ON CONFLICT)
INSERT INTO drift_configs (agent_id, drift_threshold, warning_threshold, metric_weights)
SELECT
  agent_id,
  0.30,
  0.24,
  '{"response_adherence":0.3,"constraint_violations":0.2,"toxicity_score":0.2,"hallucination_rate":0.2,"avg_response_length":0.1}'::jsonb
FROM agents
ON CONFLICT (agent_id) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────────
-- 11. Row Level Security (RLS) for new tables
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE drift_health_pings ENABLE ROW LEVEL SECURITY;
ALTER TABLE drift_configs ENABLE ROW LEVEL SECURITY;
ALTER TABLE zkp_commitments ENABLE ROW LEVEL SECURITY;
ALTER TABLE persona_history ENABLE ROW LEVEL SECURITY;

-- Service role full access policies (matches existing pattern)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE policyname = 'Service role has full access to drift_health_pings'
  ) THEN
    CREATE POLICY "Service role has full access to drift_health_pings" ON drift_health_pings
      FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE policyname = 'Service role has full access to drift_configs'
  ) THEN
    CREATE POLICY "Service role has full access to drift_configs" ON drift_configs
      FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE policyname = 'Service role has full access to zkp_commitments'
  ) THEN
    CREATE POLICY "Service role has full access to zkp_commitments" ON zkp_commitments
      FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE policyname = 'Service role has full access to persona_history'
  ) THEN
    CREATE POLICY "Service role has full access to persona_history" ON persona_history
      FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 12. Post-migration validation
-- ─────────────────────────────────────────────────────────────────────────────

-- Verify no CHECK violations exist after migration
SELECT 'drift_health_pings' AS tbl, COUNT(*) AS violations
FROM drift_health_pings
WHERE drift_score NOT BETWEEN 0 AND 1
UNION ALL
SELECT 'drift_configs', COUNT(*)
FROM drift_configs
WHERE warning_threshold >= drift_threshold
UNION ALL
SELECT 'zkp_commitments', COUNT(*)
FROM zkp_commitments
WHERE status NOT IN ('active', 'revoked');
